### ISSUE TITLE
lastRun() in Sass does not allow updating the browser

### ISSUE THREAD

**Issue by markosmk** [ToTibis/gulp4-boilerplate#4]
Hi, thank you very much for sharing this template.

I was working with it, and when using browser-sync I saw that the browser does not update when I make changes to the sass files

![image](https://user-images.githubusercontent.com/15690145/105606936-c2c4c200-5d7a-11eb-864e-61372bbd13b0.png)

when removing the lastRun () function if everything works normally

`return $.gulp.src($.path.src.sass, {since: $.gulp.lastRun('sass:development')})`

according to the documentation:
>**lastRun()**
Retrieves the last time a task was successfully completed during the current running process. Most useful on subsequent task runs while a watcher is running.
When combined with src(), enables incremental builds to speed up execution times by skipping files that haven't changed since the last successful task completion.

Maybe for the images or fonts, that's fine, since you shouldn't do the process again, but when we need changes in sass I think it can be avoided.

maybe I didn't have something in mind, tell me what you think, Greetings! I will be attentive to your answer !!

**Comment by ToTibis** [comment]
Hi Mark! I apologize for such a belated answer.

I may be wrong, but I believe that browser reloading is not necessary for sass tasks, since styles are inserted what is called on the fly. In this boilerplate, I wanted to achieve maximum performance, therefore use of the lastRun method is considered necessary.
In later commits I have integrated dependency caching of sass files which made it possible to break styles into logical parts, example: 

![Screenshot_7](https://user-images.githubusercontent.com/20776460/120487941-6e37f000-c3c7-11eb-8daa-997c14c7bfb3.png)

Anyway, I will be glad to hear your suggestions for improving this template. Let me know if I can close this issue!

P.S. Sorry for my english :)
